!SESSION 2016-12-05 02:22:49.628 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.egit.ui 2 0 2016-12-05 02:24:09.222
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\ROG VALKYRIE'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.
!SESSION 2016-12-05 02:24:15.320 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.egit.ui 2 0 2016-12-05 02:24:22.568
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\ROG VALKYRIE'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-05 02:24:24.546
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-05 02:25:18.948
!MESSAGE - Ok, file is non-null. Getting info on:C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" -u "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc\interpreterInfo.py"
- Setting task name:Making pythonpath environment... "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" -u "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc\interpreterInfo.py"
- Setting task name:Making exec... "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" -u "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc\interpreterInfo.py"
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Success getting the info. Result:<xml>
<name>python</name>
<version>3.5</version>
<executable>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe</executable>
<lib>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs</lib>
<lib>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib</lib>
<lib>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32</lib>
<lib>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_datetime</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_imp</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_opcode</forced_lib>
<forced_lib>_operator</forced_lib>
<forced_lib>_pickle</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha1</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_signal</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_stat</forced_lib>
<forced_lib>_string</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_thread</forced_lib>
<forced_lib>_tracemalloc</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winapi</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>atexit</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>builtins</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>faulthandler</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>ssl</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>winreg</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
</xml>

!STACK 0
java.lang.RuntimeException: - Ok, file is non-null. Getting info on:C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" -u "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc\interpreterInfo.py"
- Setting task name:Making pythonpath environment... "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" -u "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc\interpreterInfo.py"
- Setting task name:Making exec... "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" -u "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc\interpreterInfo.py"
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Success getting the info. Result:<xml>
<name>python</name>
<version>3.5</version>
<executable>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe</executable>
<lib>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs</lib>
<lib>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib</lib>
<lib>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32</lib>
<lib>C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_datetime</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_imp</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_opcode</forced_lib>
<forced_lib>_operator</forced_lib>
<forced_lib>_pickle</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha1</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_signal</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_stat</forced_lib>
<forced_lib>_string</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_thread</forced_lib>
<forced_lib>_tracemalloc</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winapi</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>atexit</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>builtins</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>faulthandler</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>ssl</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>winreg</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
</xml>

	at org.python.pydev.core.log.Log.logInfo(Log.java:66)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker.autoConfigSingleApply(AutoConfigMaker.java:177)
	at org.python.pydev.ui.PyProjectPythonDetails$ProjectInterpreterAndGrammarConfig$2.widgetSelected(PyProjectPythonDetails.java:289)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1120)
	at org.eclipse.swt.widgets.Link.WM_LBUTTONUP(Link.java:1035)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4828)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5102)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2552)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3814)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.actions.NewProjectAction.run(NewProjectAction.java:115)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.brainwy.liclipse.rcp.IDEApplication.start(IDEApplication.java:210)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-05 02:25:18.950
!MESSAGE Restoring info for: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe
!STACK 0
java.lang.RuntimeException: Restoring info for: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:529)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.internalRecreateCacheGetInterpreterInfos(AbstractInterpreterManager.java:345)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:655)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Expecting: K:\dev\engineering10\LiClipse Workspace\.metadata\.plugins\org.python.pydev\v1_74zpvvyvarvbq3wchsvzz45f0\modulesKeys to exist (and be a file).
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.loadFromFile(ModulesManager.java:293)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.load(SystemModulesManager.java:397)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:527)
	... 4 more

!ENTRY org.python.pydev.shared_core 1 1 2016-12-05 02:25:19.278
!MESSAGE Finished restoring information for: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe at: K:\dev\engineering10\LiClipse Workspace\.metadata\.plugins\org.python.pydev\v1_74zpvvyvarvbq3wchsvzz45f0
!STACK 0
java.lang.RuntimeException: Finished restoring information for: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe at: K:\dev\engineering10\LiClipse Workspace\.metadata\.plugins\org.python.pydev\v1_74zpvvyvarvbq3wchsvzz45f0
	at org.python.pydev.core.log.Log.logInfo(Log.java:66)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:574)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.internalRecreateCacheGetInterpreterInfos(AbstractInterpreterManager.java:345)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:655)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-12-05 02:25:19.572
!MESSAGE Info: Rebuilding internal caches: K:\dev\engineering10\LiClipse Workspace\.metadata\.plugins\com.python.pydev.analysis\python_v1_74zpvvyvarvbq3wchsvzz45f0\python.pydevsysteminfo (Expected error to be provided and got no error!)

!ENTRY org.python.pydev.shared_core 4 4 2016-12-05 02:25:33.953
!MESSAGE Info: Rebuilding internal caches: K:\dev\engineering10\LiClipse Workspace\.metadata\.plugins\org.eclipse.core.resources\.projects\SRProject\com.python.pydev.analysis\AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)

!ENTRY org.eclipse.core.jobs 4 2 2016-12-05 03:28:12.117
!MESSAGE An internal error occurred during: "LabelEventJob".
!STACK 0
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Display.error(Display.java:1262)
	at org.eclipse.swt.widgets.Display.asyncExec(Display.java:710)
	at org.eclipse.egit.ui.internal.decorators.GitLightweightDecorator.fireLabelEvent(GitLightweightDecorator.java:727)
	at org.eclipse.egit.ui.internal.decorators.LabelEventJob.run(GitLightweightDecorator.java:797)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SESSION 2016-12-07 00:21:36.762 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.egit.ui 2 0 2016-12-07 00:21:44.205
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\ROG VALKYRIE'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-07 00:21:46.142
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 01:29:36.140
!MESSAGE Unable to get project for the run
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to get project for the run
	at org.python.pydev.debug.ui.launching.PythonRunnerConfig.getProjectFromConfiguration(PythonRunnerConfig.java:337)
	at org.python.pydev.debug.ui.launching.PythonRunnerConfig.getPythonpathFromConfiguration(PythonRunnerConfig.java:361)
	at org.python.pydev.debug.ui.blocks.PythonPathBlock.initializeFrom(PythonPathBlock.java:97)
	at org.python.pydev.debug.ui.MainModuleTab.initializeFrom(MainModuleTab.java:90)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup.initializeFrom(AbstractLaunchConfigurationTabGroup.java:90)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:201)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.displayInstanceTabs(LaunchConfigurationTabGroupViewer.java:766)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer$8.run(LaunchConfigurationTabGroupViewer.java:637)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.inputChanged(LaunchConfigurationTabGroupViewer.java:654)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput0(LaunchConfigurationTabGroupViewer.java:615)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput(LaunchConfigurationTabGroupViewer.java:590)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.handleLaunchConfigurationSelectionChanged(LaunchConfigurationsDialog.java:1008)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog$4.selectionChanged(LaunchConfigurationsDialog.java:621)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:878)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:875)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1729)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1077)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView.handleConfigurationAdded(LaunchConfigurationView.java:297)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView.access$1(LaunchConfigurationView.java:286)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView$2.run(LaunchConfigurationView.java:275)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1203)
	at org.eclipse.debug.ui.DebugUITools$3.run(DebugUITools.java:629)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:637)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:570)
	at org.eclipse.debug.ui.actions.AbstractLaunchToolbarAction.runInternal(AbstractLaunchToolbarAction.java:92)
	at org.eclipse.debug.ui.actions.AbstractLaunchHistoryAction.runWithEvent(AbstractLaunchHistoryAction.java:420)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:237)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:228)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.brainwy.liclipse.rcp.IDEApplication.start(IDEApplication.java:210)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
!SUBENTRY 1 org.python.pydev.debug 4 4 2016-12-07 01:29:36.141
!MESSAGE Unable to get project for the run

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 01:30:20.970
!MESSAGE Unable to get project for the run
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to get project for the run
	at org.python.pydev.debug.ui.launching.PythonRunnerConfig.getProjectFromConfiguration(PythonRunnerConfig.java:337)
	at org.python.pydev.debug.ui.blocks.PythonPathBlock.initializeFrom(PythonPathBlock.java:83)
	at org.python.pydev.debug.ui.MainModuleTab.initializeFrom(MainModuleTab.java:90)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup.initializeFrom(AbstractLaunchConfigurationTabGroup.java:90)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:201)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.displayInstanceTabs(LaunchConfigurationTabGroupViewer.java:766)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer$8.run(LaunchConfigurationTabGroupViewer.java:637)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.inputChanged(LaunchConfigurationTabGroupViewer.java:654)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput0(LaunchConfigurationTabGroupViewer.java:615)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput(LaunchConfigurationTabGroupViewer.java:590)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.handleLaunchConfigurationSelectionChanged(LaunchConfigurationsDialog.java:1008)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog$4.selectionChanged(LaunchConfigurationsDialog.java:621)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:878)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:875)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1729)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1077)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView.handleConfigurationAdded(LaunchConfigurationView.java:297)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView.access$1(LaunchConfigurationView.java:286)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView$2.run(LaunchConfigurationView.java:275)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1203)
	at org.eclipse.debug.ui.DebugUITools$3.run(DebugUITools.java:629)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:637)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:570)
	at org.eclipse.debug.ui.actions.AbstractLaunchToolbarAction.runInternal(AbstractLaunchToolbarAction.java:92)
	at org.eclipse.debug.ui.actions.AbstractLaunchHistoryAction.runWithEvent(AbstractLaunchHistoryAction.java:420)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:237)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:228)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.brainwy.liclipse.rcp.IDEApplication.start(IDEApplication.java:210)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
!SUBENTRY 1 org.python.pydev.debug 4 4 2016-12-07 01:30:20.970
!MESSAGE Unable to get project for the run

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 01:30:20.971
!MESSAGE Could not recognize: 'org.python.pydev.django.launching.DjangoLaunchConfigurationType' using default python interpreter manager.
!STACK 0
java.lang.RuntimeException: Could not recognize: 'org.python.pydev.django.launching.DjangoLaunchConfigurationType' using default python interpreter manager.
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.debug.ui.blocks.PythonPathBlock.initializeFrom(PythonPathBlock.java:93)
	at org.python.pydev.debug.ui.MainModuleTab.initializeFrom(MainModuleTab.java:90)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup.initializeFrom(AbstractLaunchConfigurationTabGroup.java:90)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:201)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.displayInstanceTabs(LaunchConfigurationTabGroupViewer.java:766)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer$8.run(LaunchConfigurationTabGroupViewer.java:637)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.inputChanged(LaunchConfigurationTabGroupViewer.java:654)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput0(LaunchConfigurationTabGroupViewer.java:615)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput(LaunchConfigurationTabGroupViewer.java:590)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.handleLaunchConfigurationSelectionChanged(LaunchConfigurationsDialog.java:1008)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog$4.selectionChanged(LaunchConfigurationsDialog.java:621)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:878)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:875)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1729)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1077)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView.handleConfigurationAdded(LaunchConfigurationView.java:297)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView.access$1(LaunchConfigurationView.java:286)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView$2.run(LaunchConfigurationView.java:275)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1203)
	at org.eclipse.debug.ui.DebugUITools$3.run(DebugUITools.java:629)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:637)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:570)
	at org.eclipse.debug.ui.actions.AbstractLaunchToolbarAction.runInternal(AbstractLaunchToolbarAction.java:92)
	at org.eclipse.debug.ui.actions.AbstractLaunchHistoryAction.runWithEvent(AbstractLaunchHistoryAction.java:420)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:237)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:228)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.brainwy.liclipse.rcp.IDEApplication.start(IDEApplication.java:210)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

!ENTRY org.eclipse.core.resources 4 368 2016-12-07 01:51:05.779
!MESSAGE Variable references non-existent resource : ${workspace_loc:SRProject/test2.py}

!ENTRY org.python.pydev.shared_core 1 1 2016-12-07 02:12:20.365
!MESSAGE It seems it's already disposed...
!STACK 0
java.lang.RuntimeException: It seems it's already disposed...
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_ui.outline.BaseModel.setRoot(BaseModel.java:189)
	at org.python.pydev.shared_ui.outline.BaseModel$1$1.run(BaseModel.java:68)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.brainwy.liclipse.rcp.IDEApplication.start(IDEApplication.java:210)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
!SESSION 2016-12-07 02:16:14.782 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.egit.ui 2 0 2016-12-07 02:16:21.240
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\ROG VALKYRIE'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.ui 4 4 2016-12-07 02:16:22.053
!MESSAGE Conflicting handlers for org.python.pydev.editor.actions.execLineInConsole: {ActionHandler(org.python.proxies.__main__$ExecuteLine$9@a386542)} vs {ActionHandler(org.python.proxies.__main__$ExecuteLine$9@a386542)}

!ENTRY org.eclipse.ui 4 4 2016-12-07 02:16:22.053
!MESSAGE Conflicting handlers for org.python.pydev.editor.actions.execLineInConsole: {ActionHandler(org.python.proxies.__main__$ExecuteLine$9@a386542)} vs {ActionHandler(org.python.proxies.__main__$ExecuteLine$9@a386542)}

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-07 02:16:23.121
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.eclipse.core.resources 4 368 2016-12-07 02:35:07.666
!MESSAGE Variable references non-existent resource : ${workspace_loc:SRProject/test2_masterScript.py}
!SESSION 2016-12-07 02:37:35.337 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.egit.ui 2 0 2016-12-07 02:37:41.702
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\ROG VALKYRIE'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-07 02:37:43.531
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)
!SESSION 2016-12-07 04:19:05.670 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2016-12-07 04:19:12.968
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.egit.ui 2 0 2016-12-07 04:19:18.592
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\ROG VALKYRIE'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-07 04:19:20.450
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.eclipse.core.jobs 4 2 2016-12-07 18:55:50.863
!MESSAGE An internal error occurred during: "LabelEventJob".
!STACK 0
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Display.error(Display.java:1262)
	at org.eclipse.swt.widgets.Display.asyncExec(Display.java:710)
	at org.eclipse.egit.ui.internal.decorators.GitLightweightDecorator.fireLabelEvent(GitLightweightDecorator.java:727)
	at org.eclipse.egit.ui.internal.decorators.LabelEventJob.run(GitLightweightDecorator.java:797)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SESSION 2016-12-07 18:58:22.624 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 18:58:33.351
!MESSAGE Unable to resolve module for:L/SRProject/sensorLibrary.py
!STACK 0
java.lang.RuntimeException: Unable to resolve module for:L/SRProject/sensorLibrary.py
	at org.python.pydev.builder.PyDevBuilderVisitor.getModuleName(PyDevBuilderVisitor.java:211)
	at com.python.pydev.analysis.builder.AnalysisBuilderVisitor.doVisitChangedResource(AnalysisBuilderVisitor.java:174)
	at com.python.pydev.analysis.builder.AnalysisParserObserver.analyze(AnalysisParserObserver.java:180)
	at com.python.pydev.analysis.builder.AnalysisParserObserver.parserChanged(AnalysisParserObserver.java:145)
	at org.python.pydev.parser.PyParser.fireParserChanged(PyParser.java:226)
	at org.python.pydev.parser.PyParser.reparseDocument(PyParser.java:342)
	at org.python.pydev.parser.PyParser.reparseDocument(PyParser.java:1)
	at org.python.pydev.shared_core.parsing.ParserScheduler.reparseDocument(ParserScheduler.java:162)
	at org.python.pydev.shared_core.parsing.ParsingThread.run(ParsingThread.java:54)

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 18:58:33.897
!MESSAGE Unable to resolve module for:L/SRProject/masterScript.py
!STACK 0
java.lang.RuntimeException: Unable to resolve module for:L/SRProject/masterScript.py
	at org.python.pydev.builder.PyDevBuilderVisitor.getModuleName(PyDevBuilderVisitor.java:211)
	at com.python.pydev.analysis.builder.AnalysisBuilderVisitor.doVisitChangedResource(AnalysisBuilderVisitor.java:174)
	at com.python.pydev.analysis.builder.AnalysisParserObserver.analyze(AnalysisParserObserver.java:180)
	at com.python.pydev.analysis.builder.AnalysisParserObserver.parserChanged(AnalysisParserObserver.java:145)
	at org.python.pydev.parser.PyParser.fireParserChanged(PyParser.java:226)
	at org.python.pydev.parser.PyParser.reparseDocument(PyParser.java:342)
	at org.python.pydev.parser.PyParser.reparseDocument(PyParser.java:1)
	at org.python.pydev.shared_core.parsing.ParserScheduler.reparseDocument(ParserScheduler.java:162)
	at org.python.pydev.shared_core.parsing.ParsingThread.run(ParsingThread.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-07 18:58:35.130
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-07 18:58:35.134
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-07 18:58:35.134
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-07 18:58:35.134
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2016-12-07 18:58:35.316
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Levantine'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 18:58:35.409
!MESSAGE Error. returning: 0
!STACK 0
java.nio.file.NoSuchFileException: K:\dev\engineering10\LiClipse Workspace\SRProject\masterScript.py
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.getLastModifiedTime(Files.java:2266)
	at org.python.pydev.shared_core.io.FileUtils.lastModified(FileUtils.java:1059)
	at org.python.pydev.shared_core.io.FileUtils.lastModified(FileUtils.java:1050)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.addInfoToModuleOnRestoreInsertCommand(AbstractAdditionalDependencyInfo.java:525)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.processInsert(AbstractAdditionalInfoWithBuild.java:191)
	at org.python.pydev.core.DeltaSaver$DeltaInsertCommand.processWith(DeltaSaver.java:97)
	at org.python.pydev.core.DeltaSaver.processDeltas(DeltaSaver.java:317)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreSavedInfo(AbstractAdditionalInfoWithBuild.java:102)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.loadContentsFromFile(AbstractAdditionalDependencyInfo.java:495)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.load(AbstractAdditionalDependencyInfo.java:410)
	at com.python.pydev.analysis.additionalinfo.AdditionalProjectInterpreterInfo.getAdditionalInfoForProject(AdditionalProjectInterpreterInfo.java:244)
	at com.python.pydev.analysis.additionalinfo.AdditionalProjectInterpreterInfo.recreateAllInfo(AdditionalProjectInterpreterInfo.java:325)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyProjectPythonpathRestored(InterpreterObserver.java:41)
	at org.python.pydev.plugin.nature.PythonNature$RebuildPythonNatureModules.run(PythonNature.java:176)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-07 18:58:37.572
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 18:59:05.156
!MESSAGE java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 19:00:09.803
!MESSAGE Error while getting info for module:builtins. Project: P/SRProject
!STACK 0
java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:341)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:542)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:750)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:525)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:758)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1034)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:63)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:119)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:110)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 32 more

!ENTRY org.eclipse.jface.text 4 0 2016-12-07 19:12:47.180
!MESSAGE Unexpected runtime error while computing a text hover
!STACK 0
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:90)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1119)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	... 5 more
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:606)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:1)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1111)
	... 11 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 22 more

!ENTRY org.python.pydev.shared_core 4 4 2016-12-07 19:21:24.564
!MESSAGE Error while getting info for module:builtins. Project: P/SRProject
!STACK 0
java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:341)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:542)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:750)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:525)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:758)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1034)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 31 more

!ENTRY org.eclipse.jface.text 4 0 2016-12-07 20:16:48.240
!MESSAGE Unexpected runtime error while computing a text hover
!STACK 0
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:90)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1119)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	... 5 more
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:606)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:1)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1111)
	... 11 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 22 more
!SESSION 2016-12-10 17:36:34.093 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.python.pydev.shared_core 1 1 2016-12-10 17:36:57.737
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-10 17:36:57.747
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-10 17:36:57.748
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-10 17:36:57.749
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2016-12-10 17:36:58.031
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Levantine'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-10 17:37:00.079
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.python.pydev.shared_core 4 4 2016-12-10 17:37:27.847
!MESSAGE java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more
!SESSION 2016-12-10 18:01:28.949 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.python.pydev.shared_core 1 1 2016-12-10 18:01:42.663
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-10 18:01:42.672
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-10 18:01:42.673
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-10 18:01:42.673
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2016-12-10 18:01:43.168
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Levantine'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-10 18:01:45.183
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.python.pydev.shared_core 4 4 2016-12-10 18:02:12.767
!MESSAGE java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more
!SESSION 2016-12-13 16:45:57.643 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.python.pydev.shared_core 1 1 2016-12-13 16:47:34.570
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-13 16:47:34.589
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-13 16:47:34.590
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2016-12-13 16:47:34.592
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2016-12-13 16:47:34.732
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Levantine'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2016-12-13 16:47:36.762
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.python.pydev.shared_core 4 4 2016-12-13 16:48:04.678
!MESSAGE java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more
!SESSION 2017-03-18 21:16:30.572 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.python.pydev.shared_core 1 1 2017-03-18 21:16:48.326
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-03-18 21:16:48.373
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-03-18 21:16:48.402
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-03-18 21:16:48.415
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-03-18 21:16:48.624
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Levantine'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2017-03-18 21:16:50.819
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.python.pydev.shared_core 4 4 2017-03-18 21:17:18.504
!MESSAGE java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more

!ENTRY org.python.pydev.shared_core 4 4 2017-03-19 00:34:04.121
!MESSAGE Error while getting info for module:builtins. Project: P/SRProject
!STACK 0
java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:341)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:542)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:750)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:525)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:758)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1034)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 31 more
!SESSION 2017-03-19 13:53:46.141 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.python.pydev.shared_core 1 1 2017-03-19 13:54:00.166
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-03-19 13:54:00.322
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-03-19 13:54:00.432
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-03-19 13:54:00.619
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Levantine'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-03-19 13:54:00.650
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2017-03-19 13:54:02.634
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)
!SESSION 2017-03-19 15:04:09.544 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.python.pydev.shared_core 1 1 2017-03-19 15:04:28.160
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-03-19 15:04:28.206
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-03-19 15:04:28.253
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-03-19 15:04:28.269
!MESSAGE Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-03-19 15:04:28.503
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Levantine'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.brainwy.liclipsetext.shared_core 4 4 2017-03-19 15:04:30.763
!MESSAGE C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
!STACK 0
java.io.FileNotFoundException: C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\com.brainwy.liclipse.editor_3.3.0.201611281405\etc\5yz4x6m18oij9anbul5v4g4b9 (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeBytesToFile(FileUtils.java:140)
	at org.brainwy.liclipsetext.shared_core.io.FileUtils.writeStrToFile(FileUtils.java:133)
	at com.brainwy.liclipse.editor.lic.CheckRegistered.run(CheckRegistered.java:145)

!ENTRY org.python.pydev.shared_core 4 4 2017-03-19 15:04:58.363
!MESSAGE java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more

!ENTRY org.python.pydev.shared_core 4 4 2017-03-19 15:08:15.675
!MESSAGE Error while getting info for module:builtins. Project: P/SRProject
!STACK 0
java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:341)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:542)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:750)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:525)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:758)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1034)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 31 more

!ENTRY org.eclipse.jface.text 4 0 2017-03-19 15:09:23.398
!MESSAGE Unexpected runtime error while computing a text hover
!STACK 0
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:90)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1119)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	... 5 more
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:606)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:1)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1111)
	... 11 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 22 more

!ENTRY org.python.pydev.shared_core 4 4 2017-03-19 15:09:24.336
!MESSAGE Error while getting info for module:builtins. Project: P/SRProject
!STACK 0
java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:341)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:542)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:750)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:525)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:758)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1034)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 31 more

!ENTRY org.python.pydev.shared_core 4 4 2017-03-19 15:10:05.476
!MESSAGE Error while getting info for module:builtins. Project: P/SRProject
!STACK 0
java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:341)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:542)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:750)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:525)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:758)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1034)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 31 more

!ENTRY org.python.pydev.shared_core 4 4 2017-03-19 15:12:31.424
!MESSAGE Error while getting info for module:builtins. Project: P/SRProject
!STACK 0
java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:341)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:542)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:750)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:525)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:758)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1034)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:63)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:119)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:110)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 32 more

!ENTRY org.eclipse.jface.text 4 0 2017-03-19 15:12:34.675
!MESSAGE Unexpected runtime error while computing a text hover
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:90)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:606)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:1)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:947)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 20 more

!ENTRY org.eclipse.jface.text 4 0 2017-03-19 15:12:36.608
!MESSAGE Unexpected runtime error while computing a text hover
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:90)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:606)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:1)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:947)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 20 more

!ENTRY org.eclipse.jface.text 4 0 2017-03-19 15:12:40.000
!MESSAGE Unexpected runtime error while computing a text hover
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:90)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)
Caused by: java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:606)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:1)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:947)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 20 more

!ENTRY org.python.pydev.shared_core 4 4 2017-03-19 15:13:34.736
!MESSAGE Error while getting info for module:builtins. Project: P/SRProject
!STACK 0
java.io.IOException: Cannot run program "C:\Users\ROG VALKYRIE\AppData\Local\Programs\Python\Python35-32\python.exe" (in directory "C:\Program Files\Brainwy\LiClipse 3.3.0\plugins\org.python.pydev_5.4.0.201611281405\pysrc"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.editor.codecompletion.shell.PythonShell.createServerProcess(PythonShell.java:63)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:281)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:341)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:542)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:750)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:525)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:758)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:575)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:544)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:535)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1034)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:983)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:965)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:678)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:63)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:119)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:110)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 32 more
